### ISSUE TITLE
errors - backups - server

### ISSUE THREAD

**Issue by thug-thug** [Hurdock/gta5-ragemp-server#4]
i give this error:
Starting RAGE Multiplayer server...

[=========================================================]

        MaxPlayers:             20
        Sync rate:              40
        Name:                   SE-MP | Roleplay
        Gamemode:               roleplay
        Streaming distance:     300
        Announcement:           disabled
        Voice chat:             enabled
        Address:                127.0.0.1:22005
        Connection limits:      disabled
        Encryption:             disabled
        NodeJS:                 enabled
        C#:                     disabled

[=========================================================]

[N] Starting network... - OK: (IPv4-only) at 127.0.0.1:22005
(node:5824) ExperimentalWarning: The ESM module loader is experimental.
Loading packages
        "camera" loaded
        "server" loaded
[P] Plugin bridge.dll loaded!
Started HTTP server at 22006 port.
[DEBUG] Server started at Wed Nov 27 2019 07:21:28 GMT+0000 (Greenwich Mean Time)
[Data] 0 loaded.
(node:5824) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at global.loadFactions (C:\Users\Administrator\Desktop\gta5-ragemp-server\Server\packages\server\src\systems\factions\index.js:10:29)
    at prom.then (C:\Users\Administrator\Desktop\gta5-ragemp-server\Server\packages\server\src\systems\databox\index.js:29:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5824) UnhandledPromiseRejectionWarning: Unhandled
promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Business] 0 loaded.
[Houses] 0 loaded.

**Comment by thug-thug** [comment]
in vscode, i give erros on build web too, i need steps for installing this server
